import { notFound } from "next/navigation";
import { getPromptById } from "../../lib/notion";
import CopyPromptButton from "../../test-page/CopyPromptButton";

type PageProps = {
  params: Promise<{
    id: string;
  }>;
};

function formatPublishedDate(
  value: string | null
): string | null {
  if (!value) {
    return null;
  }

  const date = new Date(value);

  if (Number.isNaN(date.getTime())) {
    return value;
  }

  const parts = new Intl.DateTimeFormat(
    "en-GB",
    {
      timeZone: "Asia/Bangkok",
      day: "numeric",
      month: "long",
      year: "numeric",
      hour: "numeric",
      minute: "2-digit",
      hour12: true,
    }
  ).formatToParts(date);

  const get = (type: string) =>
    parts.find(
      (part) => part.type === type
    )?.value ?? "";

  return `${get("day")} ${get(
    "month"
  )} ${get("year")} at ${get(
    "hour"
  )}:${get("minute")} ${get(
    "dayPeriod"
  )}`;
}

export default async function PromptDetailPage({
  params,
}: PageProps) {
  const { id } = await params;

  const prompt = await getPromptById(id);

  if (!prompt) {
    notFound();
  }

  /*
   * รวมข้อความทั้งหมดของ Prompt
   *
   * Block ที่ไม่มีข้อความ เช่น Image / Video
   * จะถูกตัดออก
   */
  const fullPrompt = prompt.content
    .map((block) => block.content.trim())
    .filter(Boolean)
    .join("\n\n");

  const publishedDate = formatPublishedDate(
    prompt.publishedDate
  );

  return (
    <main
      style={{
        maxWidth: "1000px",
        margin: "0 auto",
        padding: "40px 20px 80px",
      }}
    >
      {/* =========================
          Main Image
      ========================= */}
      {prompt.mainImageUrl && (
        <div
          style={{
            marginBottom: "30px",
          }}
        >
          <img
            src={prompt.mainImageUrl}
            alt={prompt.title}
            style={{
              width: "100%",
              maxHeight: "700px",
              objectFit: "contain",
              display: "block",
              borderRadius: "16px",
            }}
          />
        </div>
      )}

      {/* =========================
          Title
      ========================= */}
      <h1
        style={{
          margin: "0 0 10px",
          fontSize: "32px",
          lineHeight: 1.3,
        }}
      >
        {prompt.title}
      </h1>

      {/* =========================
          Theme
      ========================= */}
      {prompt.category && (
        <p
          style={{
            margin: "0 0 8px",
            fontSize: "14px",
            color: "#666",
          }}
        >
          <strong>Theme:</strong>{" "}
          {prompt.category}
        </p>
      )}

      {/* =========================
          Published Date
      ========================= */}
      {publishedDate && (
        <p
          style={{
            margin: "0 0 8px",
            fontSize: "14px",
            color: "#777",
          }}
        >
          <strong>Published:</strong>{" "}
          {publishedDate}
        </p>
      )}

      {/* =========================
          Tags
      ========================= */}
      {prompt.tags.length > 0 && (
        <p
          style={{
            margin: "0 0 10px",
            fontSize: "13px",
            color: "#888",
            lineHeight: 1.6,
          }}
        >
          <strong>Tags:</strong>{" "}
          {prompt.tags.join(" · ")}
        </p>
      )}

      {/* =========================
          Generated By
      ========================= */}
      {prompt.generatedBy.length > 0 && (
        <p
          style={{
            margin: "0 0 30px",
            fontSize: "14px",
          }}
        >
          <strong>Generated by:</strong>{" "}
          {prompt.generatedBy.join(" · ")}
        </p>
      )}

      {/* =========================
          Intro Quote
      ========================= */}
      {(prompt.introTh || prompt.introEn) && (
        <blockquote
          style={{
            margin: "0 0 35px",
            padding: "18px 22px",
            borderLeft: "4px solid #222",
            background: "#f8f8f8",
            borderRadius: "0 10px 10px 0",
            color: "#555",
          }}
        >
          {prompt.introTh && (
            <p
              style={{
                margin: 0,
                whiteSpace: "pre-wrap",
                lineHeight: 1.7,
              }}
            >
              {prompt.introTh}
            </p>
          )}

          {prompt.introEn && (
            <p
              style={{
                margin:
                  prompt.introTh
                    ? "10px 0 0"
                    : 0,
                whiteSpace: "pre-wrap",
                lineHeight: 1.7,
                color: "#777",
              }}
            >
              {prompt.introEn}
            </p>
          )}
        </blockquote>
      )}

      {/* =========================
          Full Prompt
      ========================= */}
      {fullPrompt && (
        <section
          style={{
            marginBottom: "40px",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "space-between",
              gap: "16px",
              marginBottom: "12px",
            }}
          >
            <h2
              style={{
                margin: 0,
                fontSize: "24px",
              }}
            >
              Prompt
            </h2>

            <CopyPromptButton
              text={fullPrompt}
            />
          </div>

          <div
            style={{
              padding: "20px",
              background: "#f7f7f7",
              border: "1px solid #e5e5e5",
              borderRadius: "12px",
              whiteSpace: "pre-wrap",
              lineHeight: 1.7,
              fontSize: "15px",
            }}
          >
            {fullPrompt}
          </div>
        </section>
      )}

      {/* =========================
          Files & Media
      ========================= */}
      {prompt.referenceImages.length > 0 && (
        <section
          style={{
            marginBottom: "40px",
          }}
        >
          <h2
            style={{
              margin: "0 0 16px",
              fontSize: "24px",
            }}
          >
            Files & media
          </h2>

          <div
            style={{
              display: "grid",
              gridTemplateColumns:
                "repeat(auto-fit, minmax(220px, 1fr))",
              gap: "16px",
            }}
          >
            {prompt.referenceImages.map(
              (image, index) => {
                /*
                 * ใช้ API Proxy ของเว็บไซต์
                 * เพื่อไม่ให้ต้องพึ่ง Notion signed URL
                 */
                const imageUrl =
                  `/api/prompt-reference/${prompt.id}/${index}`;

                return (
                  <div
                    key={`${image.name}-${index}`}
                    style={{
                      border:
                        "1px solid #e5e5e5",
                      borderRadius: "12px",
                      overflow: "hidden",
                      background: "#fff",
                    }}
                  >
                    {image.url && (
                      <img
                        src={imageUrl}
                        alt={
                          image.name ||
                          `Reference ${index + 1}`
                        }
                        style={{
                          width: "100%",
                          aspectRatio: "1 / 1",
                          objectFit: "cover",
                          display: "block",
                        }}
                      />
                    )}

                    <div
                      style={{
                        padding: "12px",
                      }}
                    >
                      <p
                        style={{
                          margin:
                            "0 0 10px",
                          fontSize: "13px",
                          color: "#666",
                          wordBreak:
                            "break-word",
                        }}
                      >
                        {image.name ||
                          `Reference ${index + 1}`}
                      </p>

                      <a
                        href={imageUrl}
                        download
                        target="_blank"
                        rel="noopener noreferrer"
                        style={{
                          display:
                            "inline-block",
                          padding:
                            "8px 12px",
                          background: "#111",
                          color: "#fff",
                          borderRadius:
                            "8px",
                          textDecoration:
                            "none",
                          fontSize: "13px",
                        }}
                      >
                        Download
                      </a>
                    </div>
                  </div>
                );
              }
            )}
          </div>
        </section>
      )}

      {/* =========================
          Recommendation
      ========================= */}
      {prompt.recommendation && (
        <section>
          <h2
            style={{
              margin: "0 0 12px",
              fontSize: "24px",
            }}
          >
            แนะนำ
          </h2>

          <p
            style={{
              whiteSpace: "pre-wrap",
              lineHeight: 1.7,
            }}
          >
            {prompt.recommendation}
          </p>
        </section>
      )}
    </main>
  );
}