import { getPromptVault } from "../lib/notion";
import CopyPromptButton from "./CopyPromptButton";

export default async function NotionTestPage() {
  const prompts = await getPromptVault();

  return (
    <main
      style={{
        padding: "40px 20px",
        fontFamily: "sans-serif",
        maxWidth: "900px",
        margin: "0 auto",
      }}
    >
      <h1>Notion Prompt Vault Test</h1>

      <p>
        พบข้อมูล <strong>{prompts.length}</strong> รายการ
      </p>

      {prompts.map((prompt) => {
        const promptText = prompt.content
          .filter((block) => block.type !== "image")
          .map((block) => block.content)
          .filter(Boolean)
          .join("\n\n");

        // Tag structure จาก notion.ts
// year     = Tag ตัวที่ 1
// category = Tag ตัวที่ 2 → Theme
// tags     = Tag ตัวที่ 3 เป็นต้นไป → Tags จริง
const theme = prompt.category || "-";
const realTags = prompt.tags;

        // Format Published Date
        const formattedDate = prompt.publishedDate
          ? new Date(prompt.publishedDate).toLocaleDateString(
              "en-GB",
              {
                day: "numeric",
                month: "long",
                year: "numeric",
              }
            )
          : "-";

        return (
          <article
            key={prompt.id}
            style={{
              marginTop: "40px",
              padding: "20px",
              border: "1px solid #333",
              borderRadius: "12px",
            }}
          >
            {/* Title */}
            <h2
              style={{
                marginTop: 0,
                marginBottom: "12px",
              }}
            >
              {prompt.title}
            </h2>

            {/* Main Image */}
            {prompt.mainImageUrl && (
              <div style={{ marginBottom: "16px" }}>
                <img
                  src={prompt.mainImageUrl}
                  alt={prompt.title}
                  style={{
                    width: "100%",
                    maxWidth: "800px",
                    height: "auto",
                    display: "block",
                    borderRadius: "8px",
                  }}
                />
              </div>
            )}

            {/* Published Date */}
            <p>
              <strong>Published Date:</strong>{" "}
              {formattedDate}
            </p>

            {/* Theme */}
            <p>
              <strong>Theme:</strong>{" "}
              {theme}
            </p>

            {/* Intro TH */}
           {(prompt.introTh || prompt.introEn) && (
  <div
    style={{
      marginTop: "16px",
      marginBottom: "16px",
      padding: "16px 18px",
      borderLeft: "3px solid #666",
      background: "#111",
      borderRadius: "0 8px 8px 0",
      lineHeight: 1.7,
    }}
  >
    {prompt.introTh && (
      <p
        style={{
          margin: 0,
          marginBottom: prompt.introEn ? "10px" : 0,
        }}
      >
        {prompt.introTh}
      </p>
    )}

    {prompt.introEn && (
      <p
        style={{
          margin: 0,
          opacity: 0.8,
        }}
      >
        {prompt.introEn}
      </p>
    )}
  </div>
)}

            {/* Tags */}
            <p>
              <strong>Tags:</strong>{" "}
              {realTags.length > 0
                ? realTags.join(", ")
                : "-"}
            </p>

            {/* Generated By */}
            <p>
              <strong>Generated by:</strong>{" "}
              {prompt.generatedBy.length > 0
                ? prompt.generatedBy.join(", ")
                : "-"}
            </p>

            {/* Recommendation */}
            {prompt.recommendation && (
              <>
                <h3>แนะนำ</h3>

                <div
                  style={{
                    background: "#111",
                    padding: "16px",
                    borderRadius: "8px",
                    lineHeight: 1.6,
                  }}
                >
                  {prompt.recommendation}
                </div>
              </>
            )}

            {/* Prompt */}
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                marginTop: "24px",
                marginBottom: "8px",
                gap: "12px",
              }}
            >
              <h3
                style={{
                  margin: 0,
                }}
              >
                Prompt
              </h3>

              {promptText && (
                <CopyPromptButton text={promptText} />
              )}
            </div>

            <div
              style={{
                background: "#111",
                padding: "16px",
                borderRadius: "8px",
                whiteSpace: "pre-wrap",
                lineHeight: 1.6,
                overflowX: "auto",
              }}
            >
              {promptText || "ไม่มี Prompt"}
            </div>

            {/* Reference Image */}
            {prompt.imageUrl && (
              <>
                <h3
                  style={{
                    marginTop: "24px",
                    marginBottom: "10px",
                  }}
                >
                  Reference Image
                </h3>

                <div
                  style={{
                    display: "flex",
                    alignItems: "flex-start",
                    gap: "12px",
                    padding: "8px",
                    borderTop: "1px solid #333",
                  }}
                >
                  <img
                    src={prompt.imageUrl}
                    alt={`Reference image for ${prompt.title}`}
                    style={{
                      width: "120px",
                      height: "auto",
                      display: "block",
                      borderRadius: "6px",
                    }}
                  />

                  <div>
                    <a
                      href={prompt.imageUrl}
                      target="_blank"
                      rel="noopener noreferrer"
                      style={{
                        display: "inline-block",
                        padding: "8px 12px",
                        borderRadius: "6px",
                        border: "1px solid #444",
                        background: "#222",
                        color: "#fff",
                        textDecoration: "none",
                        fontSize: "14px",
                      }}
                    >
                      เปิดภาพเต็ม
                    </a>

                    <p
                      style={{
                        marginTop: "8px",
                        marginBottom: 0,
                        fontSize: "12px",
                        opacity: 0.6,
                      }}
                    >
                      เปิดภาพเต็มเพื่อบันทึกภาพต้นฉบับ
                    </p>
                  </div>
                </div>
              </>
            )}
          </article>
        );
      })}
    </main>
  );
}